### ISSUE TITLE
Toggle for AutounlockX support 

### ISSUE THREAD

**Issue by robertybob** [1DI4R/Youup#5]
Hello. Would it be possible to add a toggle for this tweak to ignore the presence of AutounlockX? I would much prefer to have to still enter a sum instead of the phone unlocking and alarm stopping when looking directly at my phone - therefore bypassing the alarm and risking me falling back to sleep

**Comment by 0xdbug** [comment]
What version of You up? are you using?

The newest update You up? 1.5.8 (which i submitted yesterday) fixed that conflict with AUX. Please reinstall/update the tweak.
